### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-multisite#1]
How is this intended to be used? I just set up multi-site and want to enforce that all sites use the DT theme. Since the comments in this file say it is a plugin, I put it in `/wp-content/plugins/disciple-tools-multisite/disciple-tools-multisite.php`. However, when I go to create a new site, I get this error:

```
Notice: Constant WP_DEFAULT_THEME already defined in /var/www/html/wp-content/plugins/disciple-tools-multisite/disciple-tools-multisite.php on line 12

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/disciple-tools-multisite/disciple-tools-multisite.php:12) in /var/www/html/wp-includes/pluggable.php on line 1219
```

**Comment by corsacca** [comment]
@cairocoder01 Sorry for net seeing this comment before. I think this commit will have fixed your issue:
https://github.com/DiscipleTools/disciple-tools-multisite/commit/18b2e48afacd7b0bcfe8e9fe7f8be7fd25deb7e7
